import type { ObjectType } from "@/types/garden";

export type VoiceZooEntryStatus = "prototype" | "planned";

export type VoiceZooEntry = {
  objectType: ObjectType;
  name: string;
  ruby: string;
  icon: string;
  catalogImageSrc: string;
  stageVideoSrc: string;
  price: number;
  status: VoiceZooEntryStatus;
  soundDesign: string;
  visualReaction: string;
  memo: string;
};

export const VOICE_ZOO_ENTRIES: VoiceZooEntry[] = [
  {
    objectType: "furin",
    name: "風鈴",
    ruby: "ふうりん",
    icon: "furin",
    catalogImageSrc: "/images/garden/objects/furin/catalog/huurine.png",
    stageVideoSrc: "/videos/garden/objects/furin/stage/huurin.webm",
    price: 180,
    status: "prototype",
    soundDesign: "声を軽く高域寄りにして、透明感のある余韻へ変換（段階的に実装）",
    visualReaction: "音量に応じて短冊が揺れる。現在はメーター反応を先行実装。",
    memo: "収音UIは接続済み。音色変換はこれから強化。",
  },
  {
    objectType: "shishi-odoshi",
    name: "鹿威し",
    ruby: "ししおどし",
    icon: "shishi-odoshi",
    catalogImageSrc: "/images/garden/objects/shishi-odoshi/catalog/sisiodosie.png",
    stageVideoSrc: "/videos/garden/objects/shishi-odoshi/stage/sisiodosi.webm",
    price: 260,
    status: "planned",
    soundDesign: "声エネルギーを水量に見立て、一定量で竹が落ちる打撃音を合成",
    visualReaction: "溜まり -> 落下 -> 反動の周期アニメーションで反応",
    memo: "図鑑の先行登録。次フェーズでオブジェクト挙動を実装。",
  },
  {
    objectType: "kane",
    name: "鐘",
    ruby: "かね",
    icon: "kane",
    catalogImageSrc: "/images/garden/objects/kane/catalog/kanee.png",
    stageVideoSrc: "/videos/garden/objects/kane/stage/kane.webm",
    price: 300,
    status: "planned",
    soundDesign: "低域を強調した余韻で鐘の響きを模したボイス変換",
    visualReaction: "報酬タイミングで鐘の揺れを動画で再生",
    memo: "新規素材追加済み。音響チューニング待ち。",
  },
  {
    objectType: "obake",
    name: "おばけ",
    ruby: "おばけ",
    icon: "obake",
    catalogImageSrc: "/images/garden/objects/obake/catalog/obakee.png",
    stageVideoSrc: "/videos/garden/objects/obake/stage/obake.webm",
    price: 280,
    status: "planned",
    soundDesign: "フォルマント変調でふわっとした幽霊声を演出",
    visualReaction: "報酬タイミングでふわふわ移動する動画を再生",
    memo: "新規素材追加済み。ループ尺は後で最適化。",
  },
  {
    objectType: "hanabi",
    name: "花火",
    ruby: "はなび",
    icon: "hanabi",
    catalogImageSrc: "/images/garden/objects/hanabi/catalog/hanabie.png",
    stageVideoSrc: "/videos/garden/objects/hanabi/stage/hanabi.webm",
    price: 320,
    status: "planned",
    soundDesign: "声の立ち上がりを花火の打ち上げに見立て、余韻を拡張して広がりを演出",
    visualReaction: "報酬タイミングで火花のループ動画を短時間再生",
    memo: "新規素材追加済み。挙動調整は次フェーズで実施。",
  },
  {
    objectType: "tyo-tyo",
    name: "蝶々",
    ruby: "ちょうちょ",
    icon: "tyo-tyo",
    catalogImageSrc: "/images/garden/objects/tyo-tyo/catalog/tyoutyoe.png",
    stageVideoSrc: "/videos/garden/objects/tyo-tyo/stage/tyoutyo.webm",
    price: 240,
    status: "planned",
    soundDesign: "高域寄りの軽い変調で羽ばたき感を表現",
    visualReaction: "報酬タイミングで羽ばたき動画を再生",
    memo: "新規素材追加済み。移動軌道表現は次で対応。",
  },
  {
    objectType: "kaeru",
    name: "蛙",
    ruby: "かえる",
    icon: "kaeru",
    catalogImageSrc: "/images/garden/objects/kaeru/catalog/kaerue.png",
    stageVideoSrc: "/videos/garden/objects/kaeru/stage/kaeru.webm",
    price: 220,
    status: "planned",
    soundDesign: "低域を少し残した反復ディレイで蛙の鳴きの間を表現",
    visualReaction: "再生時に軽く上下する動画を短時間再生",
    memo: "画像追加済み。動画素材の最終版待ち。",
  },
  {
    objectType: "hue",
    name: "笛",
    ruby: "ふえ",
    icon: "hue",
    catalogImageSrc: "/images/garden/objects/hue/catalog/huee.png",
    stageVideoSrc: "/videos/garden/objects/hue/stage/hue.webm",
    price: 260,
    status: "planned",
    soundDesign: "中高域を持ち上げた息感のある笛風トーンへ変換",
    visualReaction: "再生時に笛のアニメーション動画を再生",
    memo: "画像・動画ともに追加済み。",
  },
  {
    objectType: "suzume",
    name: "雀",
    ruby: "すずめ",
    icon: "suzume",
    catalogImageSrc: "/images/garden/objects/suzume/catalog/suzumee.png",
    stageVideoSrc: "/videos/garden/objects/suzume/stage/suzume.webm",
    price: 240,
    status: "planned",
    soundDesign: "短い断続音を重ねてさえずり感を演出",
    visualReaction: "再生時に羽ばたき動画を再生",
    memo: "素材追加後に最終調整予定。",
  },
  {
    objectType: "sansin",
    name: "三線",
    ruby: "さんしん",
    icon: "sansin",
    catalogImageSrc: "/images/garden/objects/sansin/catalog/sansine.png",
    stageVideoSrc: "/videos/garden/objects/sansin/stage/sansin.webm",
    price: 340,
    status: "planned",
    soundDesign: "アタックを強調して弦のはじき感を加える",
    visualReaction: "再生時に弾くモーション動画を再生",
    memo: "素材追加後に音響バランス調整予定。",
  },
  {
    objectType: "mattya",
    name: "抹茶",
    ruby: "まっちゃ",
    icon: "mattya",
    catalogImageSrc: "/images/garden/objects/mattya/catalog/mattyae.png",
    stageVideoSrc: "/videos/garden/objects/mattya/stage/mattya.webm",
    price: 210,
    status: "planned",
    soundDesign: "柔らかいローパスで落ち着いた湯気感を演出",
    visualReaction: "再生時に湯気が立つ動画を再生",
    memo: "素材追加後に反応速度を調整予定。",
  },
  {
    objectType: "semi",
    name: "蝉",
    ruby: "せみ",
    icon: "semi",
    catalogImageSrc: "/images/garden/objects/semi/catalog/semie.png",
    stageVideoSrc: "/videos/garden/objects/semi/stage/semi.webm",
    price: 250,
    status: "planned",
    soundDesign: "帯域を絞った連続成分で蝉しぐれ感を再現",
    visualReaction: "再生時に羽の振動動画を再生",
    memo: "画像・動画ともに追加済み。",
  },
  {
    objectType: "takibi",
    name: "焚き火",
    ruby: "たきび",
    icon: "takibi",
    catalogImageSrc: "/images/garden/objects/takibi/catalog/takibie.png",
    stageVideoSrc: "/videos/garden/objects/takibi/stage/takibi.webm",
    price: 330,
    status: "planned",
    soundDesign: "ノイズ成分を足して薪のはぜる質感を表現",
    visualReaction: "再生時に火のゆらぎ動画を再生",
    memo: "素材追加後にループ継ぎ目を最適化予定。",
  },
  {
    objectType: "akimusi",
    name: "秋虫",
    ruby: "あきむし",
    icon: "akimusi",
    catalogImageSrc: "/images/garden/objects/akimusi/catalog/akimusie.png",
    stageVideoSrc: "/videos/garden/objects/akimusi/stage/akimusi.webm",
    price: 230,
    status: "planned",
    soundDesign: "高域中心の細い連続音で虫の声を演出",
    visualReaction: "再生時に小さな点滅動画を再生",
    memo: "画像・動画ともに追加済み。",
  },
  {
    objectType: "ka",
    name: "蚊",
    ruby: "か",
    icon: "ka",
    catalogImageSrc: "/images/garden/objects/ka/catalog/kae.png",
    stageVideoSrc: "/videos/garden/objects/ka/stage/ka.webm",
    price: 9999,
    status: "planned",
    soundDesign: "高周波寄りの揺らぎで羽音の存在感を演出",
    visualReaction: "再生時に素早く動く動画を再生",
    memo: "素材追加後に画面占有率を小さく調整予定。",
  },
  {
    objectType: "huro",
    name: "風呂",
    ruby: "ふろ",
    icon: "huro",
    catalogImageSrc: "/images/garden/objects/huro/catalog/huroe.png",
    stageVideoSrc: "/videos/garden/objects/huro/stage/huro.webm",
    price: 290,
    status: "planned",
    soundDesign: "低域を残した湯気感のあるリバーブで入浴空間の響きを演出",
    visualReaction: "再生時に湯気の揺らぎ動画を再生",
    memo: "画像・動画追加済み。音色チューニング待ち。",
  },
  {
    objectType: "suzu",
    name: "鈴",
    ruby: "すず",
    icon: "suzu",
    catalogImageSrc: "/images/garden/objects/suzu/catalog/suzue.png",
    stageVideoSrc: "/videos/garden/objects/suzu/stage/suzu.webm",
    price: 200,
    status: "planned",
    soundDesign: "高域の短い余韻を重ねて鈴のきらめきを表現",
    visualReaction: "再生時に小刻みに揺れる動画を再生",
    memo: "画像・動画追加済み。",
  },
  {
    objectType: "haka",
    name: "墓",
    ruby: "はか",
    icon: "haka",
    catalogImageSrc: "/images/garden/objects/haka/catalog/hakae.png",
    stageVideoSrc: "/videos/garden/objects/haka/stage/haka.webm",
    price: 310,
    status: "planned",
    soundDesign: "残響を長めにして静かな重厚感を演出",
    visualReaction: "再生時に淡いゆらぎ動画を再生",
    memo: "画像・動画追加済み。",
  },
  {
    objectType: "hagoita",
    name: "羽子板",
    ruby: "はごいた",
    icon: "hagoita",
    catalogImageSrc: "/images/garden/objects/hagoita/catalog/hagoitae.png",
    stageVideoSrc: "/videos/garden/objects/hagoita/stage/hagoita.webm",
    price: 270,
    status: "planned",
    soundDesign: "アタックを強調し、軽快な打音感を追加",
    visualReaction: "再生時に羽子板が弾む動画を再生",
    memo: "画像・動画追加済み。",
  },
  {
    objectType: "youkai",
    name: "妖怪",
    ruby: "ようかい",
    icon: "youkai",
    catalogImageSrc: "/images/garden/objects/youkai/catalog/youkoe.png",
    stageVideoSrc: "/videos/garden/objects/youkai/stage/youko.webm",
    price: 360,
    status: "planned",
    soundDesign: "フォルマントを揺らして不気味さのある質感に変換",
    visualReaction: "再生時にふわっと出現する動画を再生",
    memo: "画像・動画追加済み。",
  },
  {
    objectType: "kame",
    name: "亀",
    ruby: "かめ",
    icon: "kame",
    catalogImageSrc: "/images/garden/objects/kame/catalog/kamee.png",
    stageVideoSrc: "/videos/garden/objects/kame/stage/kame.webm",
    price: 230,
    status: "planned",
    soundDesign: "ゆっくりしたピッチ変動でのんびりした質感を演出",
    visualReaction: "再生時にゆっくり動く動画を再生",
    memo: "画像・動画追加済み。",
  },
  {
    objectType: "saru",
    name: "猿",
    ruby: "さる",
    icon: "saru",
    catalogImageSrc: "/images/garden/objects/saru/catalog/sarue.png",
    stageVideoSrc: "/videos/garden/objects/saru/stage/saru.webm",
    price: 280,
    status: "planned",
    soundDesign: "中域を前に出して賑やかな鳴き声感を演出",
    visualReaction: "再生時に跳ねる動画を再生",
    memo: "画像・動画追加済み。",
  },
  {
    objectType: "tako",
    name: "蛸",
    ruby: "たこ",
    icon: "tako",
    catalogImageSrc: "/images/garden/objects/tako/catalog/takoe.png",
    stageVideoSrc: "/videos/garden/objects/tako/stage/tako.webm",
    price: 260,
    status: "planned",
    soundDesign: "柔らかいローパスで水中感のある音像に変換",
    visualReaction: "再生時にゆらゆら漂う動画を再生",
    memo: "画像・動画追加済み。",
  },
];

export const VOICE_ZOO_ENTRY_BY_OBJECT_TYPE = Object.fromEntries(
  VOICE_ZOO_ENTRIES.map((entry) => [entry.objectType, entry]),
) as Record<ObjectType, VoiceZooEntry>;

export function getVoiceZooObjectPrice(objectType: ObjectType) {
  return VOICE_ZOO_ENTRY_BY_OBJECT_TYPE[objectType].price;
}
